services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
      - /app/node_modules
